version: '3.8'
services:
  server:
    depends_on:
    - db
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - ./server/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # TODO use env variable to protect password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/database_init:/docker-entrypoint-initdb.d/

volumes:
  db_data:
    driver: local

# debug commands
# psql -h localhost -p 5432 -U postgres
# psql -h localhost -p 5432 -U server_user -d appdb
# dc exec db sh
